services:
  - type: web
    name: kpms-magic-rpg
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18
    plan: free
